name: frontend
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  go_router: ^6.2.0
  flutter_hooks: ^0.18.6
  cached_network_image: ^3.2.3
  riverpod_annotation: ^2.0.1
  flutter_dropzone: ^3.0.5
  dotted_border: ^2.0.0+3
  uuid: ^3.0.7
  path_provider: ^2.0.13
  font_awesome_flutter: ^10.4.0
  dartz: ^0.10.1
  dio: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.1.3
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_verify: ^3.1.0
  go_router_builder: ^1.1.6

flutter:
  uses-material-design: true
