services:
  # Backend service (HTTP server, ML models)
  backend:
    container_name: gp_backend
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/.venv
    ports:
      - "3002:80"
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [ gpu ]
              count: 1

  # Redis service (message broker & backend)
  redis:
    image: redis:alpine
    container_name: gp_redis
