# Start from base image (OS): Python based on Debian
FROM python:3.11

# Install libgl1-mesa-glx (required by matplotlib)
RUN apt update && apt install -y libgl1-mesa-glx

# Set working directory
WORKDIR /app

# Expose port
EXPOSE 80

# Run application
ENTRYPOINT [ "./entry_point.sh" ]

# Create virtual environment if not exists
RUN python -m venv .venv

# Copy requirements.txt to container
COPY requirements.txt ./

# Install python dependencies
RUN --mount=type=cache,target=/root/.cache/pip \
    . .venv/bin/activate && \
    pip install -r requirements.txt